### ISSUE TITLE
IE tests do not run on IE 11 with IEDriverServer 2.43

### ISSUE THREAD

**Issue by AnastasiaKorol** [darthKwisatzHaderach/SpecFlowExample#3]
IE test (after including webdriver to the project) do not run at all:

Given User open ABBYY web site
-> done: SiteSearchSteps.GivenUserOpenGlobalWebSite() (3.5s)
And fill Search field with query "Languages and Dictionaries"
-> error: PageObjectBase: The Page Title doesnt match.

At the same time Firefox tests run successfully, so the site didn't change.

IE 11
IEDriverServer 2.43
OS Windows 8.1 Pro 64-bit

**Comment by darthKwisatzHaderach** [comment]
For correct work IEDriver required to disable protected mode in browser version 10 or higher. I added some code to do that from tests. The tests must be run with administrator rights.
